/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.springboot.cloud.nsclcservice.nsclc.thrift.predict;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-04-12")
public class PredictInfo implements org.apache.thrift.TBase<PredictInfo, PredictInfo._Fields>, java.io.Serializable, Cloneable, Comparable<PredictInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PredictInfo");

  private static final org.apache.thrift.protocol.TField FEATURE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("featurePath", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PREDICT_RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("predictResult", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PredictInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PredictInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String featurePath; // optional
  public int predictResult; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FEATURE_PATH((short)1, "featurePath"),
    PREDICT_RESULT((short)2, "predictResult");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FEATURE_PATH
          return FEATURE_PATH;
        case 2: // PREDICT_RESULT
          return PREDICT_RESULT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PREDICTRESULT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.FEATURE_PATH,_Fields.PREDICT_RESULT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FEATURE_PATH, new org.apache.thrift.meta_data.FieldMetaData("featurePath", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "String")));
    tmpMap.put(_Fields.PREDICT_RESULT, new org.apache.thrift.meta_data.FieldMetaData("predictResult", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PredictInfo.class, metaDataMap);
  }

  public PredictInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PredictInfo(PredictInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFeaturePath()) {
      this.featurePath = other.featurePath;
    }
    this.predictResult = other.predictResult;
  }

  public PredictInfo deepCopy() {
    return new PredictInfo(this);
  }

  @Override
  public void clear() {
    this.featurePath = null;
    setPredictResultIsSet(false);
    this.predictResult = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getFeaturePath() {
    return this.featurePath;
  }

  public PredictInfo setFeaturePath(@org.apache.thrift.annotation.Nullable java.lang.String featurePath) {
    this.featurePath = featurePath;
    return this;
  }

  public void unsetFeaturePath() {
    this.featurePath = null;
  }

  /** Returns true if field featurePath is set (has been assigned a value) and false otherwise */
  public boolean isSetFeaturePath() {
    return this.featurePath != null;
  }

  public void setFeaturePathIsSet(boolean value) {
    if (!value) {
      this.featurePath = null;
    }
  }

  public int getPredictResult() {
    return this.predictResult;
  }

  public PredictInfo setPredictResult(int predictResult) {
    this.predictResult = predictResult;
    setPredictResultIsSet(true);
    return this;
  }

  public void unsetPredictResult() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PREDICTRESULT_ISSET_ID);
  }

  /** Returns true if field predictResult is set (has been assigned a value) and false otherwise */
  public boolean isSetPredictResult() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PREDICTRESULT_ISSET_ID);
  }

  public void setPredictResultIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PREDICTRESULT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
      case FEATURE_PATH:
        if (value == null) {
          unsetFeaturePath();
        } else {
          setFeaturePath((java.lang.String)value);
        }
        break;

      case PREDICT_RESULT:
        if (value == null) {
          unsetPredictResult();
        } else {
          setPredictResult((java.lang.Integer)value);
        }
        break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
      case FEATURE_PATH:
        return getFeaturePath();

      case PREDICT_RESULT:
        return getPredictResult();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
      case FEATURE_PATH:
        return isSetFeaturePath();
      case PREDICT_RESULT:
        return isSetPredictResult();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PredictInfo)
      return this.equals((PredictInfo)that);
    return false;
  }

  public boolean equals(PredictInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_featurePath = true && this.isSetFeaturePath();
    boolean that_present_featurePath = true && that.isSetFeaturePath();
    if (this_present_featurePath || that_present_featurePath) {
      if (!(this_present_featurePath && that_present_featurePath))
        return false;
      if (!this.featurePath.equals(that.featurePath))
        return false;
    }

    boolean this_present_predictResult = true && this.isSetPredictResult();
    boolean that_present_predictResult = true && that.isSetPredictResult();
    if (this_present_predictResult || that_present_predictResult) {
      if (!(this_present_predictResult && that_present_predictResult))
        return false;
      if (this.predictResult != that.predictResult)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetFeaturePath()) ? 131071 : 524287);
    if (isSetFeaturePath())
      hashCode = hashCode * 8191 + featurePath.hashCode();

    hashCode = hashCode * 8191 + ((isSetPredictResult()) ? 131071 : 524287);
    if (isSetPredictResult())
      hashCode = hashCode * 8191 + predictResult;

    return hashCode;
  }

  @Override
  public int compareTo(PredictInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetFeaturePath()).compareTo(other.isSetFeaturePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeaturePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.featurePath, other.featurePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPredictResult()).compareTo(other.isSetPredictResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredictResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predictResult, other.predictResult);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PredictInfo(");
    boolean first = true;

    if (isSetFeaturePath()) {
      sb.append("featurePath:");
      if (this.featurePath == null) {
        sb.append("null");
      } else {
        sb.append(this.featurePath);
      }
      first = false;
    }
    if (isSetPredictResult()) {
      if (!first) sb.append(", ");
      sb.append("predictResult:");
      sb.append(this.predictResult);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PredictInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PredictInfoStandardScheme getScheme() {
      return new PredictInfoStandardScheme();
    }
  }

  private static class PredictInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<PredictInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PredictInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // FEATURE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.featurePath = iprot.readString();
              struct.setFeaturePathIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PREDICT_RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.predictResult = iprot.readI32();
              struct.setPredictResultIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PredictInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.featurePath != null) {
        if (struct.isSetFeaturePath()) {
          oprot.writeFieldBegin(FEATURE_PATH_FIELD_DESC);
          oprot.writeString(struct.featurePath);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetPredictResult()) {
        oprot.writeFieldBegin(PREDICT_RESULT_FIELD_DESC);
        oprot.writeI32(struct.predictResult);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PredictInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PredictInfoTupleScheme getScheme() {
      return new PredictInfoTupleScheme();
    }
  }

  private static class PredictInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<PredictInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PredictInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFeaturePath()) {
        optionals.set(0);
      }
      if (struct.isSetPredictResult()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFeaturePath()) {
        oprot.writeString(struct.featurePath);
      }
      if (struct.isSetPredictResult()) {
        oprot.writeI32(struct.predictResult);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PredictInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.featurePath = iprot.readString();
        struct.setFeaturePathIsSet(true);
      }
      if (incoming.get(1)) {
        struct.predictResult = iprot.readI32();
        struct.setPredictResultIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

